name: Release
on:
  push:
    branches:
      - 'master'
    tags:
      - '20*'  # e.g., 2023.01+dfsg-2
  pull_request:
    branches:
      - 'master'
jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - run: "./extract.sh"
      - run: cat _artifacts/SHA256SUMS
      - run: (cd _artifacts; sha256sum SHA256SUMS)
      - name: "Prepare the release note"
        run: |
          tag="${GITHUB_REF##*/}"
          shasha=$(sha256sum _artifacts/SHA256SUMS | awk '{print $1}')
          cat <<-EOF | tee /tmp/release-note.txt
          ${tag}

          The license (GPL-2.0) is included in the \`*.orig.tar.gz\` source archive.

          - - -
          The binaries were built automatically on GitHub Actions.
          The build log is available for 90 days: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          The sha256sum of the SHA256SUMS file itself is \`${shasha}\` .
          EOF
      - name: "Create release"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/20')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF##*/}"
          asset_flags=()
          for f in _artifacts/*; do asset_flags+=("-a" "$f"); done
          hub release create "${asset_flags[@]}" -F /tmp/release-note.txt --draft "${tag}"
